name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build # 빌드 명령 명시
      - env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: npm start