name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: ls -la dist # 빌드 디렉토리 확인
      - run: ls -la dist/public || echo "client/dist not found"
      - env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: npm start